FROM mcr.microsoft.com/devcontainers/python:0-3.11

# More info: https://containers.dev/guide/dockerfile

RUN echo `pwd`
RUN ls -l
RUN pip3 install jupyterlab jupyter-book ghp-import plotly pandas altair bokeh
RUN pip3 install transformers
